export default {
  UNAUTHORIZED: 'UNAUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  EMAIL_NOT_FOUND: 'EMAIL_NOT_FOUND',
  INVALID_EMAIL_TOKEN: 'INVALID_EMAIL_TOKEN',
};
